# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: d28e7a11194398f01632e9c7e2f60cab27023af1472670d4acb2d9816f34c93e502296c4efeb0aae010eeeb04ceb22fc3297b66fd503e6fd6301012637cf7b0b

stripe: 
  public_key: "pk_test_51QSaZOC1n0hLE0wgSYnRJ37v9IPsODnKg2FOAhbEpF4qys8J4yhM6z2TXY34Vs24Xgi2u8MiVOsoRIOIFa5kWXpG001vszHQbi"
  secret_key: "sk_test_51QSaZOC1n0hLE0wgJRz0m8zrGHOlw6D820sPPJmOzYjcuZdvkDbjISArSgxvfw7Cx7SFLqalcTYsW2HdBJjnvMNe00OYKd9DRq"